[package]
name = "real-estate-backend"
version = "0.1.0"
edition = "2018"
authors = ["Austin Parge <austin.parge@gmail.com>"]
description = "Real estate smart contract backend"
license = "MIT"

[dependencies]
soroban-sdk = "0.1"
rocket = "0.5"

[lib]
path = "src/main.rs"
